version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: adventure-db
    environment:
      POSTGRES_DB: adventure_db 
      POSTGRES_USER: adventure_user
      POSTGRES_PASSWORD: adventure_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./testData:/docker-entrypoint-initdb.d

volumes:

  postgres_data:
